version: "3.6"
services:
  bmstusa-app:
    build: "./"
    command: ./backend
    ports:
      - "8080:8080"
    depends_on:
#      - postgres-db
      - redis-db

# for remote
#  postgres-db:
#    restart: always
#   image: postgres:latest
#   environment:
#     - POSTGRES_PASSWORD=password
#  ports:
#    - "5432:5432"
  
  redis-db:
    restart: always
    image: redis:latest
    ports:
      - "6380:6379"

    