version: "3.6"
services:
  bmstusa-app:
    build: "./"
    command: ./backend
    ports:
      - "8080:8080"
    depends_on:
#      - postgres-db
      - redis-db

  auth:
    build:
      context: ./ 
      dockerfile: ./microservice/auth/Dockerfile
    command: "./auth"
    ports:
      - "8081:8081"
    depends_on:
      - redis-db

  event:
    build:
      context: ./ 
      dockerfile: ./microservice/event/Dockerfile
    command: "./event"
    ports:
      - "8083:8083"

  user:
    build:
      context: ./ 
      dockerfile: ./microservice/user/Dockerfile
    command: "./user"
    ports:
      - "8084:8084"

# for remote
#  postgres-db:
#    restart: always
#   image: postgres:latest
#   environment:
#     - POSTGRES_PASSWORD=password
#  ports:
#    - "5432:5432"
  
  redis-db:
    restart: always
    image: redis:latest
    ports:
      - "6380:6379"

    