global:
  scrape_interval:     120s
  evaluation_interval: 120s

scrape_configs:
  - job_name: bmstusa
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: 
        - bmstusa-app:8080