auth_port: "8081"

postgres_db:
    user: "postgres"
    host: "95.163.212.36"
    port: "5432"
    password: password
    dbname: "postgres"
    sslmode: "disable"


redis_db_session:
    addr: "localhost:6379"
    db_id: 0
