bmstusa_port: "8080"

auth_port: "8081"

user_port: "8084"

event_port: "8083"

postgres_db:
    user: "postgres"
    host: "postgres-db"
    port: "5432"
    password: password
    dbname: "postgres"
    sslmode: "disable"


redis_db_session:
    addr: "redis-db:6379"
    db_id: 0

