bmstusa_port: "8080"

auth_port: "8081"
auth_host: "auth"

user_port: "8084"
user_host: "user"

event_port: "8083"
event_host: "event"

postgres_db:
    user: "postgres"
    #for remote 95.163.212.36
    #for new postgres-db
    host: "95.163.212.36"
    port: "5432"
    password: password
    dbname: "postgres"
    sslmode: "disable"

main_host:
    "http://127.0.0.1:3000"

#main_host:
#    "https://bmstusssa.herokuapp.com"