port: "8080"

postgres_db:
    user: "postgres"
    host: "localhost"
    port: "5432"
    password: password
    dbname: "postgres"
    sslmode: "disable"


redis_db_session:
    addr: "localhost:6379"
    db_id: 0

redis_db_csrf:
    addr: "localhost:6379"
    db_id: 1
